BillNumberAndDate_SVG = 
VAR _SVG_Setup = 
    "data:image/svg+xml;utf8,<svg width='150' height='60' xmlns='http://www.w3.org/2000/svg'>"

VAR _BillNumber = 'Billing'[Bill Number]
VAR _BillDate = 'Billing'[Bill Date]

RETURN
_SVG_Setup &
"
    <!-- Bill Number in larger font -->
    <text x='5' y='28' font-family='Arial' font-size='14' fill='" & [Color_MediumGray] & "'>" & _BillNumber & "</text>

    <!-- Bill Date in grey -->
    <text x='5' y='48' font-family='Arial' font-size='12' fill='" & [Color_LightGray] & "'>" & FORMAT(_BillDate, "dd-MMM-yyyy") & "</text>
</svg>
